apiVersion: v1
kind: Secret
metadata:
  name: logging-web-service-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
{% for key, value in secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}