version: "3.8"

services:
  load-balancer:
    image: nginx
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:443"
      start_period: 5s
      interval: 5s
      timeout: 3s
    depends_on:
      logging-web-service:
        condition: service_healthy
    ports:
      - 443:443
      - 80:80
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/files:/www/data"
      - "./docker-compose/scripts:/opt/scripts"

  logging-web-service:
    image: ghcr.io/ruchira088/logging-web-service:main
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:8000"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 8000:8000
    volumes:
      - ./src/main/resources/logback.xml:/opt/data/logback.xml
      - ./docker-compose/scripts:/opt/scripts

  fluent-bit:
    image: fluent/fluent-bit:1.8
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./fluent-bit/logs:/opt/logs
      - ./fluent-bit/db:/opt/fluent-bit/db

  elasticsearch:
    image: elasticsearch:7.17.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      timeout: 5s
      interval: 10s
      retries: 20
      start_period: 10s
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      "discovery.type": "single-node"

  kibana:
    image: kibana:7.17.5
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

#  mongo:
#    image: mongo
#
#  graylog:
#    image: graylog/graylog:4.3
#    ports:
#      - 9000:9000
#      - 1514:1514        # Syslog TCP
#      - 1514:1514/udp    # Syslog UDP
#      - 12201:12201      # GELF TCP
#      - 12201:12201/udp  # GELF UDP
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    environment:
#      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
#      GRAYLOG_MONGODB_URI: "mongodb://mongo:27017/graylog"
#      GRAYLOG_PASSWORD_SECRET: "my-password-secret"
#      GRAYLOG_ROOT_PASSWORD_SHA2: "5d3c54e0f3ef9542edbb9835c9afb77a0538d1b413b976071175ca4434d8ad44" # root-password
