version: "3.8"

services:

  logging-web-service:
    image: logging-web-service:latest
    ports:
      - 8000:8000

  fluent-bit:
    image: fluent/fluent-bit:1.8
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./fluent-bit/logs:/opt/logs
