version: "3.8"

services:
  load-balancer:
    image: nginx
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:443"
      start_period: 5s
      interval: 5s
      timeout: 3s
    depends_on:
      logging-web-service:
        condition: service_healthy
    ports:
      - 443:443
      - 80:80
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/files:/www/data"
      - "./docker-compose/scripts:/opt/scripts"

  logging-web-service:
    image: ghcr.io/ruchira088/logging-web-service:main
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:8000"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 8000:8000
    volumes:
      - ./src/main/resources/logback.xml:/opt/data/logback.xml
      - ./docker-compose/scripts:/opt/scripts

  fluent-bit:
    image: fluent/fluent-bit:1.8
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./fluent-bit/logs:/opt/logs
      - ./fluent-bit/db:/opt/fluent-bit/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      timeout: 5s
      interval: 10s
      retries: 20
      start_period: 10s
    environment:
      "discovery.type": "single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
