version: "3.8"

services:

  logging-web-service:
#    build: .
    image: logging-web-service:latest
    ports:
      - 8000:8000
#      - 5005:5005
    volumes:
      - "./src/main/resources/logback.xml:/opt/data/logback.xml"
#      - "~/.sbt:/root/.sbt"
#      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#      #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#      #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
#      - ".:/opt/logging-web-service"
#      - "/opt/logging-web-service/target"
#      - "/opt/logging-web-service/project/target"
#      - "/root/.sbt/1.0/plugins"
