FROM openjdk:17.0.1-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/logging-web-service

ADD logging-web-service-*.tgz .

EXPOSE 8000

CMD [ "/opt/logging-web-service/bin/logging-web-service" ]
