FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/logging-web-services

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/logging-web-service

ADD logging-web-service-*.tgz .

EXPOSE 8000

CMD [ "/opt/logging-web-service/bin/logging-web-service" ]
